<div style="background-color:#f2f2f2; border-left: 8px solid #2e8b57; padding: 20px; border-radius: 10px; font-family: Arial, sans-serif;">

<center>

<h1 style="color:#2e8b57;">Introducción a la programación en Python</h1>
<h2 style="color:#2e8b57;">Instituto Mexicano del Petróleo</h2>

<p style="font-size:16px; color:#333;">
<strong>Dra. Gabriela Berenice Díaz Cortés</strong><br>
<em>gbdiaz@imp.mx</em>
</p>

<p style="font-size:16px; color:#333;">
<strong>Dr. Luis Antonio López Peña</strong><br>
<em>llopezp@imp.mx</em>
</p>

<p style="font-size:15px; color:#555;">
Dirección de Investigación <br>
Gerencia de Investigación en Explotación
</p>

</center>

</div>


# Librerías
Como se mencionó anteriormente, las librerias son conjuntos de funciones específicas, algunas de ellas son:

<img src="https://github.com/gbdiazc/Images/blob/f2031a840a330db98a65ac392e85a34acd040904/wrapper.png?raw=1" width="600">
    

## Instalación de librerías en equipo local
Se puede crear el **entorno virtual** instalando desde la creación las librerías o crear el entorno virtual e ir añadiendo las librerías. Por temas de compatibilidad es recomendado crear el environment con todas las librerías requeridas.

En windows o linux se abre la terminal (*Anaconda Prompt* en windows), y se siguen los siguientes pasos:


Crear entorno virtual con librerías: 

`\$conda create -n my_env python=3.5 numpy sympy`

<img src="https://github.com/gbdiazc/Images/blob/933cad2a83e4b2ca815eea6dbf80faedc77e7f33/anaconda_promt.png?raw=1" width="600">

Para revisar qué entornos se han creado con Conda, se puede usar el comando 

`conda env list` o `conda info --envs`

Activar entorno virtual:

`\$conda activate my_env`

Para revisar las librerías disponibles en un entorno, puedes usar

`conda list`

Instalar más librerías:

`(my_env)\$conda install sympy`

Instalar jupyter-notebook:

`(my_env)\$conda install -c conda-forge jupyterlab`

Abrir jupyter-notebook:

`(my_env)\$jupyter-notebook`



## Instalar librerías en Anaconda navigator

Se selecciona el entorno virtual y se buscan las librerías requeridas

<img src="https://github.com/gbdiazc/Images/blob/6a8676672527a82efef51a8598ffd84c9255b71c/libreria.png?raw=1" width="600">
    

Se instalan las librerías requeridas

<img src="https://github.com/gbdiazc/Images/blob/4a3ec3fde040e6181b82be8d9382c7321e031b43/install_libreria.png?raw=1" width="600">

## Sympy

Para llamar la librería de cálculo simbolico [sympy], esta se importa como sigue 

\begin{array}{llL} 
import  & \text{sympy }            &    as &   \text{ sp}\\ 
\end{array}

Su propósito es realizar cálculos de manera simbolica, es decir con variables que no tienen un valor definido de la forma mas sencilla posible, estas variables simbolicas se tienen que declarar de forma explícita.

Esta librería es capas de simplificar expresiones, calcular derivadas, integrales, limites, resolver ecuaciones, trabajar con matrices, etc.

[sympy]: https://www.sympy.org/en/index.html


In [3]:
from sympy import symbols, factor, simplify,expand
x, y = symbols('x y')
expr = x + 2*y
expr


x + 2*y

In [4]:
expr + 1

x + 2*y + 1

In [5]:
expr - x

2*y

In [6]:
x*expr

x*(x + 2*y)

In [7]:
expr1 = 2*x*expr+2*y*expr
print(expr1)


2*x*(x + 2*y) + 2*y*(x + 2*y)


In [8]:
simplify(expr1)

2*(x + y)*(x + 2*y)

In [9]:
factor(expr1) 

2*(x + y)*(x + 2*y)

In [10]:
expand(expr1)

2*x**2 + 6*x*y + 4*y**2

In [11]:
x, y = symbols('x y')
expr = x**2 + 2*x + 1 + y*x + y 
factored_expr = factor(expr)
print("Expresión original:", expr)
print("Expresión factorizada con factor():", factored_expr)


Expresión original: x**2 + x*y + 2*x + y + 1
Expresión factorizada con factor(): (x + 1)*(x + y + 1)


In [12]:
simplified_expr = simplify(expr)
print("Expresión original:", expr)
print("Expresión simplificada con simplify():", simplified_expr)

Expresión original: x**2 + x*y + 2*x + y + 1
Expresión simplificada con simplify(): x**2 + x*y + 2*x + y + 1


**Ejercicio**
Crea las siguientes variables de manera simbólica

$z = 3x + 8y + 2xy + x^2 + y^2$

$w = 7x + 2y + 2xy + x^2 + y^2$

suma ambas expresiones y simplificalas


In [15]:
from sympy import symbols, factor, simplify,expand
x, y = symbols('x y')
z = 3*x + 8*y + 2*x*y + x**2 + y**2
w = 7*x + 2*y + 2*x*y + x**2 + y**2
expr = z + w
expr

2*x**2 + 4*x*y + 10*x + 2*y**2 + 10*y

In [16]:
simplify(expr)

2*x**2 + 4*x*y + 10*x + 2*y**2 + 10*y


## Numpy 


Con la librería de [numpy] se pueden crear vectores y matrices de la siguiente forma:


* Vector con N entradas 

    `x = np.array([1, 2, ..., N])`

* Vector en un intervalo dado [init,fin] en pasos de tamaño step, si el paso es 1 se puede omitir el step 

    `x = np.array(init,fin,step) `

    `x = np.array(init,fin)` 
 
* Vector con N ceros    

    `x = np.zeros(N)`


* Vector con N unos  

   ` x = np.ones(N)`
    
    
* Matriz con (N,N) entradas 

   `A = np.array(([1, 2, ..., N],[1, 2, ..., N],[1, 2, ..., N],[1, 2, ..., N]))`

[numpy]: https://www.numpy.org/devdocs/user/quickstart.html

In [19]:
# Ejemplos
import numpy as np
N = 4

# Vector con 4 entradas distintas de cero
x = np.array([1, 2, 3, 4])
print('x = {}'.format(x))
print('tTipo de variable: {}'.format(type(x)))

x = [1 2 3 4]
tTipo de variable: <class 'numpy.ndarray'>


In [22]:
# Vector con 4 entradas iguales a cero
x = np.zeros(N)
print('x = {}'.format(x))


x = [0. 0. 0. 0.]


In [27]:
# Vector con 4 entradas iguales a uno
x = np.ones(N)
print('x = {}'.format(x))


x = [1. 1. 1. 1.]


In [28]:
# Vector con numeros enteros del 0 al N
x = np.arange(0,N+1,2)
print('x = {}'.format(x))


x = [0 2 4]


In [29]:
# Vector conmultiplos de 5 del 0 al 100
x = np.arange(0,100,5)
print('x = {}'.format(x))



x = [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [31]:
# Vector con 4 entradas aleatorias
x = np.random.random(N)
print('x = {}'.format(x))

x = [0.63612725 0.31108457 0.60700125 0.10515884]


In [32]:
# Seleccionar un elemento del vector x
x_0 = x[0]
print('x = {}'.format(x_0))


x = 0.6361272463871952


In [33]:
# Invertir el vector x
x_1 = x[::-1]
print('x = {}'.format(x_1))


x = [0.10515884 0.60700125 0.31108457 0.63612725]


In [36]:
# Encontrar los indices que no son ceros de un vector
x = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
# nz = np.argwhere( x!=0 )
nz = np.argwhere( x%2 == 0 )
print('El vector x = {} no es cero en:\n nz = {}'.format(x,nz))

El vector x = [ 1  2  4  2  4  0  1  0  0  0 12  4  5  6  7  0] no es cero en:
 nz = [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [13]
 [15]]


In [38]:
print('x[1] = {}'.format(x[1]))

x[1] = 2


In [43]:
A0 = np.array(([1,2,3],
               [4,5,6],
               [7,8,9]))
A0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# Crear una matriz 3x3 con valores de 0 a 8
A = np.arange(0,9).reshape(3,3)
print('A = \n{}'.format(A))
print('Tipo de variable: {}'.format(type(A)))

A = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Tipo de variable: <class 'numpy.ndarray'>


In [47]:
# Matrix de cuatro por cuatro
A = np.array(([1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]))
print('A = \n{}'.format(A))


A = 
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [52]:
# Matriz de numeros aleatorios de 3x3x3
A = np.random.random((3,3,3))
print('A = \n{}'.format(A))


A = 
[[[0.48316387 0.6250789  0.80384036]
  [0.08356574 0.7194419  0.78740105]
  [0.06894726 0.19465116 0.98744326]]

 [[0.53508812 0.49311347 0.88533878]
  [0.58273537 0.71148833 0.3697821 ]
  [0.43543942 0.27979596 0.522446  ]]

 [[0.73126201 0.99394903 0.95732262]
  [0.21153678 0.40452357 0.90599951]
  [0.05461126 0.20928743 0.05727722]]]


In [76]:
x = np.array([1,2,3])
a = 2
y = []
for xi in x:
    print(xi)
    y.append(xi*a)
print(y)
b = a*x
print(b)

1
2
3
[np.int64(2), np.int64(4), np.int64(6)]
[2 4 6]


In [78]:
x_vec = np.array(x)
print(f'a = {a}')
y_vec = a*x_vec
y_vec

a = 2


array([2, 4, 6])

In [65]:
# Multplicación escalar vector
x = np.arange(0,100,5)
a = 10
print(x)
print(a)
print(a*x)


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
10
[  0  50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850
 900 950]


In [67]:
# Producto punto
x = np.array([2,2,2])
y = np.array([2,2,2])
c = np.dot(x,y)
print(c, 'producto punto')

12 producto punto


In [71]:
# Multiplicación matriz vector
A = np.arange(0,9).reshape(3,3)
x = np.arange(0,3)
b = np.dot(A,x)
print(A, 'A')
print(x, 'x')
print(b, 'b')

[[0 1 2]
 [3 4 5]
 [6 7 8]] A
[0 1 2] x
[ 5 14 23] b


In [73]:
# Operaciones con arreglos

x = np.array([2,2,2])
y = np.exp(x)
z = np.sqrt(x)

print(y,'y')
print(z,'z')

[7.3890561 7.3890561 7.3890561] y
[1.41421356 1.41421356 1.41421356] z


**Ejercicio**
Crear un vector con valores dentro del rango 10 a 100 en pasos de 5

Invierte el vector 

In [91]:
vector = np.arange(10,105,5)
vector

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [94]:
vector_inv = vector[::-1]
vector_inv

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10])

**Ejercicio** Suma los elementos de la siguiente matriz

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
     

In [139]:
A = np.array(([1,2,3],
               [4,5,6],
               [7,8,9]))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
suma = 0
for fil in range(0,len(A)):
    for col in range(0,len(A)):
        suma = int(suma + A[fil][col])

print(f'la suma de todos los elementos de la matriz es {suma}')

la suma de todos los elementos de la matriz es 45


In [146]:
sum = int(np.sum(A))
print(sum)

45


### Condición np.where

Regresa una tupla con los indices del arreglo numpy en donde se cumple la condición

In [ ]:
import numpy as np
import random

x = np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print('x: ',x )

In [ ]:
idx = np.where(x>5)
print('Índices en donde x > 5 : ',idx)

In [ ]:
print('Valores en donde x > 5 : ',x[idx])

También se pueden poner dos condiciones

In [ ]:
idx = np.where((x>5) & (x<9))
print('Índices en donde x > 5 y x < 9 : ',idx)
x[idx]

Se pueden sustituir los valores seleccionados por un valor dado

In [ ]:
print('x: ',x )
x[idx] = 0
print('Sustitir por cero valores en donde x > 5 y x < 9: \n x:',x)

**Ejercicio**
Crea un arreglo de numpy que contenga los primeros 9 número naturales. Considera el cero como un número natural. 

Modifica el arreglo para que en las posiciones impares se le asigne el número -1

Modifica el arreglo unidimensional en un arreglo de 2 dimensiones de 3x3, en donde los primeros 3 elementos del arreglo unidimensional sería el primer reglón del arreglo de 2 dimensiones

### Dos condiciones np.where (condicion, [x, y])

Donde la condición es verdadera, produce x, donde no produce y

In [ ]:
x = np.array([2, 6, 5, 9, 3, 9, 4, 6, 1, 8])
print('x_{original}: ',x )

In [ ]:
idx = np.where((x>5) & (x<9))
print('Índices en donde x > 5 y x < 9 : ',idx)

In [ ]:
x1 = np.where((x>5) & (x<9), -1, x)
print('x_{nuevo}: ',x1)

**Ejercicio**
Considera los siguientes arreglos de numpy

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

¿Que se obtiene al aplicar el comando np.where(a==b)?

Explica el significado de lo que resulta al aplicar el comando anterior

Escribe los elementos del arreglo numpy b, que tienen valores entre 2 y 5

## Se pueden comparar dos arreglos

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print('a: ',a )
print('b: ',b )

In [ ]:
idx = np.where(a==b)
tidx = type(np.where(a==b))
print("a es igual a b en las entradas: ",idx," que son de tipo: ", tidx)

In [ ]:
print('a[idx]: ',a[idx] )
print('b[idx]: ',b[idx] )

### Máscaras en numpy 

In [ ]:
x = np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print('x: ',x )
print((x>5) & (x<9))

In [ ]:
y = (x>5) & (x<9)
print('y: ',y )

In [ ]:
print('Valores en donde x > 5 y x < 9: \n x:',x[y])

In [ ]:
x[y] = 0
print('Sustitir por cero valores en donde x > 5 y x < 9: \n x:',x)

### Comparación entre arreglos bi dimensionales

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print('a: \n',a )
print('b: \n',b )

In [ ]:
d = a == b
print('d es la matriz que nos muestra donde son iguales a y b, \n d:\n',d )
print("tipo de d: ",type(d))
print("tamaño de d: ",np.shape(d))

In [ ]:
print("mostrar las entradas en donde a==b : ",np.where(a==b))

In [ ]:
print("valor de las entradas en donde a==b : ",a[d])

In [ ]:
print("valor de las entradas en donde a==b : ",a[0,1])

In [ ]:
a1 = a<5
print("valor de a en donde a<5\n",a1)

In [ ]:
a1 = a<5
print("entradas de a en donde a<5\n",a[a1])

In [ ]:
print(" a:\n",a)
a[a1]=0
print("cambiar entradas de a en donde a<5 por cero\n a:\n",a)

### np.where con arreglos bidimensionales

In [ ]:
c = np.random.randint(1,10,(3,3))
d = np.random.randint(1,10,(3,3))
print('c: \n',c )
print('d: \n',d )

In [ ]:
c = np.where(c==d, c, 10)
print("sustituir las entradas diferentes en c y d por 10\nc:\n",c)

In [ ]:
print('d: \n',d )
d = np.where(d<5, 10,d)
print(np.where(d<5))
print("sustituir las entradas en d menores que 5\nd:\n",d)

**Ejercicio** 
Crea dos arreglos al azar A y B de tamaño 3x3, verificar si los arreglos son iguales componente a componente.

Verifica si los arreglos son iguales

**Ejercicio**
Construye dos matrices de enteros entre 1 y 10, A y B de tamaño 10x10, puedes usar el comando 

```
np.random.randint(min,max,(N,N))
```



**Ejercicio**
Encuentra que entradas de los arreglos anteriores son iguales (si es que hay sustituye el valor en a por "equal")

# Visualización
### Graficas 2D
Python cuenta con varias librerias que contienen funciones predefinidas. Para usarlas, se tienen que importar con la función *import*. En este curso se utilizará una libreria con funciones matemáticas [numpy] y una librería para graficar [matplotlib](https://matplotlib.org/gallery/index.html#gallery). Si el nombre de la librería es muy largo, se pueden renombrar con *as*.

\begin{array}{llL} 
import  & \text{numpy }            &    as &   \text{ np}\\ 
import  & \text{matplotlib.pyplot }&    as &   \text{ plt}\\ 
\end{array}

#### Matplotlib
Esta librería sirve para graficar funciones, la sintaxis básica es:

import matplotlib.pyplot as plt
%matplotlib notebook

* Graficar x vs y 

*plt.plot(x,y)*
* Agregar título 

*plt.title('Grafica de x vs y', fontsize=16)*
* Agregar nombre al eje x 

*plt.xlabel('Valores', fontsize=14)*
* Agregar nombre al eje y 

*plt.ylabel('Promedios', fontsize=14)*
* Mostrar la gráfica

*plt.show()*

In [ ]:
# Ejemplo: Gráfica de la función $f(x)= 2x^2$

import numpy as np
import matplotlib.pyplot as plt
N = 10
x = np.array([x for x in range(N)]) 
y = 2 * x**2
plt.plot(x,y)
plt.title('Grafica de x vs $f(x)$', fontsize=16)
plt.xlabel('x', fontsize=14)
plt.ylabel('$f(x)$', fontsize=14)
plt.show()


In [ ]:
N = 10

[x for x in range(N)]

In [ ]:
x = []
for xi in range(N):
    x.append(xi)
print(x,type(x))  
x= np.array(x)
print(x,type(x)) 
y = 2 * x**2
print(y,type(y)) 

Para modificar las lineas o el color, se pueden agregar opciones extra en la instrucción de graficar. Por ejemplo podemos agregar 'ro' para poner circulos rojos 

In [ ]:
N = 10
plt.style.use('_classic_test_patch')
plt.figure(figsize = (5,4))
x = np.array([x for x in range(N)]) 
#x = np.linspace(0,N, 100)
y = 2 * x**2
plt.plot(x,y,linewidth=1,color= "hotpink",marker='o', markersize=3,linestyle=':')
plt.title('Grafica de x vs $f(x)$', fontsize=16)
plt.xlabel('x')
plt.ylabel('$f(x)$')
plt.show()

Las posibilidades se muestran a continuación


| Symbol  | Description  | Symbol  |  Description |
|:---:|:---:|:---:|:---:|
|  b | blue  |  T |  T |
|  g | green |  s | square  |
|  r |  red |  d |  diamond |
|  c |  cyan |  v | triangle (down)  |
|  m |  magenta | ^  | triangle (up)   |
|  y |  yellow | <  | triangle (left)   |
|  k | black  |  > |  triangle (right)  |
|  w |  white | p  | pentagram  |
|  . |  point |  h |  hexagram |
|  o |  circle | -  |  solid |
|  x | x-mark  |  : |  dotted |
|  + |  plus | -.  | dashdot  |
|  * |  star |  --  | dashed  |


Tambien se pueden cambiar cualquier parte de la figura, el tamaño, los nombres de los ejes, su tamaño, con *fontsize*. 

In [ ]:
N = 10
plt.figure(figsize = (8,6))
x = np.array([x for x in range(N)]) 
#x = np.linspace(0,N, 100)
y = 2 * x**2
plt.plot(x,y,'ro')
plt.title('Grafica de x vs $f(x)$', fontsize=20)
plt.xlabel('x', fontsize=14)
plt.ylabel('$f(x)$', fontsize=14)
plt.show()

Existen unos estilos predefinidos que tienen valores dados, las posibilidades se encuentran como sigue: 

In [ ]:
print(plt.style.available)

In [ ]:
plt.style.use('_classic_test_patch')
plt.figure(figsize = (10,6))
N = 10
x = np.array([x for x in range(N)]) 
#x = np.linspace(0,N, 100)
y = 5 * x**2
plt.plot(y, 'bo')
y =  x**3
plt.plot(y,'g*')
plt.title('Grafica de x vs $f(x)$')
plt.xlabel('x')
plt.ylabel('$f(x)$')
plt.show()

Se puede agregar los nombres de cada grafica, usando la función *legend* y agregando un argumento llamado *label* en el comando de graficar *plot*. La función leyenda también toma el argumento *loc* para indicar en donde se ubican los nombres.

In [ ]:
plt.style.use('_classic_test_patch')
plt.figure(figsize = (10,6))
N = 10
x = np.array([x for x in range(N)]) 
#x = np.linspace(0,N, 100)
y = 5 * x**2
plt.plot(x, y, 'bo', label = '$f(x) = 5x^2$')
y =  x**3
plt.plot(x, y, 'r*', label = '$f(x) = x^3$')
plt.title('Grafica de x vs $f(x)$')
plt.xlabel('x')
plt.ylabel('$f(x)$')
plt.legend(loc = 0)
plt.show()

También se pueden cambiar los límites de cada eje usando las funciones *xlim* o *ylim*, y agregar la funcion *grid* para agregar una malla a la figura. 


In [ ]:

plt.figure(figsize = (8,6))
N = 10
x = np.array([x for x in range(N)]) 
#x = np.linspace(0,N, 100)
y = 5 * x**2
plt.plot(x, y, 'bo', label = '$f(x) = 5x^2$')
y =  x**3
plt.plot(x, y, 'r*', label = '$f(x) = x^3$')
plt.title('Grafica de x vs $f(x)$')
plt.xlabel('x')
plt.ylabel('$f(x)$')
plt.legend(loc = 2)

plt.xlim(-5,12)
plt.ylim(-100,800)
plt.grid()
plt.show()

Se puede hacer una tabla de graficas en una sola figura con la función  *subplot* que tiene 3 entradas: 
- Número de renglones 
- Número de columnas
- Cual elemento de la tabla se va a graficar

Adicionalmente, hay varias funciones que se pueden para realizar graficas específicas: 
- *scatter*:  es similar a plot solo que usa siempre circulos, scatter(x,y) es equivalente a  plot(x,y,'o')
- *bar*: grafica barras centradas en x con altura y
- *loglog*: escala logaritmica en los ejes x y y
- *semilogx*: escala logaritmica en el eje x
- *semilogy*: escala logaritmica en el eje 

In [ ]:
plt.style.use('_classic_test_patch')
x = np.arange(11)
y = x**2

plt.figure(figsize = (14, 8))

plt.subplot(2, 3, 1)
plt.plot(x,y)
plt.title('Plot')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid()

plt.subplot(2, 3, 2)
plt.scatter(x,y)
plt.title('Scatter')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid()

plt.subplot(2, 3, 3)
plt.bar(x,y)
plt.title('Bar')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid()

plt.subplot(2, 3, 4)
plt.loglog(x,y)
plt.title('Loglog')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid(which='both')

plt.subplot(2, 3, 5)
plt.semilogx(x,y)
plt.title('Semilogx')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid(which='both')

plt.subplot(2, 3, 6)
plt.semilogy(x,y)
plt.title('Semilogy')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid()

plt.tight_layout()

plt.show()

Para guardar las figuras se usa la función `plt.savefig`. 

In [ ]:
plt.figure(figsize = (8,6))
plt.plot(x,y)
plt.xlabel('X')
plt.ylabel('Y')
plt.savefig('figura.jpg') # pdf, jpg, png ...

## Gráficas 3D
Para hacer gráficas en 3D con matplotlib, se tiene que importar la herramienta *mplot3d*, que permite que matplotlib haga gráficas en 3D.

Para crear los ejes en 3D se usa la función *ax = plt.axes(projection='3d')* y se agregan datos, nombres de los ejes, etc.



In [ ]:
import numpy as np
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
fig = plt.figure(figsize = (10,10))
ax = plt.axes(projection='3d')
plt.show()

In [ ]:
fig = plt.figure(figsize = (8,8))
ax = plt.axes(projection='3d')
ax.grid()
t = np.arange(0, 10*np.pi, np.pi/50)
x = np.sin(t)
y = np.cos(t)

ax.plot3D(x, y, t)
ax.set_title('3D Parametric Plot')

# Set axes label
ax.set_xlabel('x', labelpad=20)
ax.set_ylabel('y', labelpad=20)
ax.set_zlabel('t', labelpad=20)

plt.show()

Para crear la malla es necesario convertir los vectores en matrices, esto se hace con la función *meshgrid*

In [ ]:
x = [1, 2, 3, 4]
y = [3, 4, 5]
X, Y = np.meshgrid(x, y)
print(X)

In [ ]:
print(Y)

Para graficar superficies, se usa la función *plot_surface(X,Y,Z)*, en donde la malla se genera con la función *meshgrid*, and $Z = f (X,Y)$ or $Z (i,j) = f (X (i,j),Y (i,j))$.
Tambien se puede agregar un mapa de color [colormap][] con la opcion *plt.cm.cividis* en el comando que grafica la superficie.

[colormap]:https://matplotlib.org/stable/tutorials/colors/colormaps.html

In [ ]:
fig = plt.figure(figsize = (12,10))
ax = plt.axes(projection='3d')

x = np.arange(-5, 5.1, 0.2)
y = np.arange(-5, 5.1, 0.2)

X, Y = np.meshgrid(x, y)
Z = np.sin(X)*np.cos(Y)

#surf = ax.plot_surface(X, Y, Z, cmap = plt.cm.cividis)
surf = ax.plot_surface(X, Y, Z, cmap = plt.cm.hsv)

# Ejes
ax.set_xlabel('x', labelpad=20)
ax.set_ylabel('y', labelpad=20)
ax.set_zlabel('z', labelpad=20)

fig.colorbar(surf, shrink=0.2, aspect=7)

plt.show()

**Ejercicio**
Graficar las funciones $f(x) = x^2$ y $f(x) = x^3$ en el intervalo $-5\le x \le 5$ con distintos colores, agregar el nombre de cada función como etiqueta y poner una malla.


**Ejercicio**
Realiza la grafica de las siguientes funciones en una sola figura (como sub plots) y pon como título la función que se esta graficando, y agrega nombre a los ejes, grafica en el intervalo $-5\le x \le 5$, agrega una malla 
*   $f(x) = x^2$ 
*   $f(x) = x^3$ 
*   $f(x) = x^4$ 
*   $f(x) = x^5$ 


# Números de punto flotante
Los números reales se almacenan como números flotantes. Los números de punto flotante son números como $\pi \approx 3.141 592 6$, o el número de Avogadro $\approx 6.03 × 10^{23}$, o la carga de un electrón $\approx 1.602 1773 3 × 10 ^{-19} $ coulombs.

Estos tienen la forma

$$±x \times b ^e$$

donde $x$, las cifras significativas o *mantisa*, *e* es el exponente y *b* es la base del sistema de punto flotante. Si la mantisa está en el rango de 1 a m, entonces tiene la forma

$$x = x_0x_1 x_2 x_3 . . . x_{m−1}$$

en base b donde cada $x_i$ es un dígito de base-b (0, 1, 2, . . . , b − 1) y m es la longitud de la mantisa.

La longitud de la mantisa describe con qué precisión se pueden aproximar los números. Ya que

$$x \times b^e = (x_0x_1 x_2 x_3 . . . x_{m−1} \text{ base b) }\times b^e$$
$$= (x_0 + x_1 b^{ −1} + x_2 b^{−2 }+ x_3 b^{−3 }+ · · · + x_{m−1} b^{ −m+1} )\times b^e .$$



El sistema de punto flotante más conocido y más utilizado es el **sistema de punto flotante IEEE**, que a veces se denomina estándar IEEE 754.

Esto especifica un conjunto de tres formatos diferentes de punto flotante: *precisión simple*, *precisión doble* y *precisión extendida*.

La mayoría de los lenguajes de programación admiten sistemas de punto flotante de precisión simple y doble. Por lo general, los tipos real o float representan números de precisión simple, mientras que los tipos double, double precision o long real/longreal representan números de precisión doble.

**Rango de los números de punto flotante:** ¿cuáles son los números de punto flotante más grande y más pequeño?

Esto depende del rango del exponente. Si $−e_{max} \leq e \leq +e_{max}$ y $1/b \leq x < 1$,
entonces el número representable más grande está cerca de $b^{e_{max}}$ y el número representable más pequeño es $b^{ −e_ {max} −1}$. Por lo general, se da $b^{e_{ max}}$ para indicar el rango de los números de punto flotante.

<img src="https://github.com/gbdiazc/Images/blob/e1e312c42286e801604e2d213e75df88633ddeaa/fp.png?raw=1" width="600">



In [ ]:
import numpy as np
print(2**15)
x = np.float16(2**15)
#x = np.float16(2**16)
x

In [ ]:
print(2**127)
x = np.single(2**127)
#x = np.single(2**128)
print(x)

In [ ]:
print(2**1023)
x = float(2**1023)
#x = float(2**1024)
print(x)

In [ ]:
print(2**1024)
x = np.double(2**1023)
#x = np.double(2**1024)
#x = np.longdouble(2**1024)
print(x)#

In [ ]:
print(2**1023)
x = np.longdouble(2**1023)
x = np.longdouble(2**1024)
print(x)